import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateLeavePDF = (leave, user = null) => {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, W, 46, "F");
  doc.setFillColor(124, 58, 237);
  doc.rect(0, 42, W, 4, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.setTextColor(255, 255, 255);
  doc.text("StaffSync", 18, 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(199, 210, 254);
  doc.text("Employee Management Platform", 18, 30);

  doc.setFillColor(255, 255, 255);
  doc.roundedRect(W - 66, 9, 54, 26, 5, 5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(79, 70, 229);
  doc.text("APPROVED LEAVE SLIP", W - 39, 19, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(107, 114, 128);
  doc.text(
    `Generated: ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}`,
    W - 39, 27, { align: "center" }
  );

  let y = 58;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.setTextColor(30, 27, 75);
  doc.text("LEAVE APPROVAL CERTIFICATE", W / 2, y, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text(
    "This document certifies that the following leave has been officially approved.",
    W / 2, y + 7, { align: "center" }
  );

  y += 16;
  doc.setDrawColor(199, 210, 254);
  doc.setLineWidth(0.5);
  doc.line(18, y, W - 18, y);

  y += 10;
  doc.setFillColor(238, 242, 255);
  doc.roundedRect(18, y, W - 36, 28, 5, 5, "F");
  doc.setFillColor(79, 70, 229);
  doc.roundedRect(18, y, 5, 28, 3, 3, "F");

  const empName  = leave.user?.name  || user?.name  || "Employee";
  const empEmail = leave.user?.email || user?.email || "—";
  const empRole  = leave.user?.role  || user?.role  || "Employee";

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 27, 75);
  doc.text(empName, 28, y + 11);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(107, 114, 128);
  doc.text(`${empRole}  ·  ${empEmail}`, 28, y + 19);

  doc.setFillColor(199, 210, 254);
  doc.roundedRect(W - 56, y + 7, 30, 10, 4, 4, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(67, 56, 202);
  doc.text(empRole.toUpperCase(), W - 41, y + 13.5, { align: "center" });

  y += 38;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(30, 27, 75);
  doc.text("Leave Details", 18, y);

  const fmt = (d) =>
    new Date(d).toLocaleDateString("en-IN", {
      weekday: "long", day: "2-digit", month: "long", year: "numeric",
    });

  autoTable(doc, {
    startY: y + 5,
    head: [["Field", "Details"]],
    body: [
      ["Leave Type",  leave.leaveType || "—"],
      ["From Date",   fmt(leave.fromDate)],
      ["To Date",     fmt(leave.toDate)],
      ["Duration",    `${leave.daysRequested || 1} working day(s)`],
      ["Reason",      leave.reason || "—"],
      ["Applied On",  new Date(leave.createdAt).toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })],
      ["Status",      "✓  APPROVED"],
    ],
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
      cellPadding: 5,
    },
    bodyStyles: {
      fontSize: 9,
      cellPadding: 5,
      textColor: [55, 65, 81],
    },
    alternateRowStyles: { fillColor: [238, 242, 255] },
    columnStyles: {
      0: { fontStyle: "bold", textColor: [79, 70, 229], cellWidth: 40 },
    },
    styles: { lineColor: [199, 210, 254], lineWidth: 0.3 },
    margin: { left: 18, right: 18 },
    theme: "grid",
    didParseCell: (data) => {
      if (data.section === "body" && data.row.index === 6 && data.column.index === 1) {
        data.cell.styles.textColor = [5, 150, 105];
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fontSize  = 10;
      }
    },
  });

  let finalY = doc.lastAutoTable.finalY + 12;

  doc.setFillColor(209, 250, 229);
  doc.setDrawColor(16, 185, 129);
  doc.setLineWidth(1.2);
  doc.roundedRect(18, finalY, W - 36, 22, 7, 7, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(5, 150, 105);
  doc.text("✓  LEAVE OFFICIALLY APPROVED", W / 2, finalY + 9, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(16, 185, 129);
  doc.text(
    "This certificate is system-generated by StaffSync and is valid without a physical signature.",
    W / 2, finalY + 16, { align: "center" }
  );

  finalY += 32;
  doc.setDrawColor(209, 213, 219);
  doc.setLineWidth(0.4);

  doc.line(18, finalY + 18, 78, finalY + 18);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(79, 70, 229);
  doc.text("Employee Signature", 48, finalY + 24, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(107, 114, 128);
  doc.text(empName, 48, finalY + 30, { align: "center" });

  doc.line(W - 78, finalY + 18, W - 18, finalY + 18);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(79, 70, 229);
  doc.text("Authorized Signatory", W - 48, finalY + 24, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(107, 114, 128);
  doc.text("Manager / HR Department", W - 48, finalY + 30, { align: "center" });

  doc.setFillColor(238, 242, 255);
  doc.rect(0, H - 14, W, 14, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(107, 114, 128);
  doc.text(
    `StaffSync  ·  Confidential  ·  Generated on ${new Date().toLocaleString("en-IN")}`,
    W / 2, H - 5, { align: "center" }
  );

  const safeName = empName.replace(/\s+/g, "_");
  const safeType = (leave.leaveType || "Leave").replace(/\s+/g, "_");
  doc.save(`LeaveSlip_${safeName}_${safeType}.pdf`);
};

export const generateReimbursementPDF = (reimbursement, user = null) => {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  doc.setFillColor(124, 58, 237);
  doc.rect(0, 0, W, 46, "F");
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 42, W, 4, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.setTextColor(255, 255, 255);
  doc.text("StaffSync", 18, 22);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(221, 214, 254);
  doc.text("Expense Reimbursement Platform", 18, 30);

  doc.setFillColor(255, 255, 255);
  doc.roundedRect(W - 66, 9, 54, 26, 5, 5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(124, 58, 237);
  doc.text("REIMBURSEMENT SLIP", W - 39, 19, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(107, 114, 128);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}`, W - 39, 27, { align: "center" });

  let y = 58;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.setTextColor(30, 27, 75);
  doc.text("EXPENSE REIMBURSEMENT REPORT", W / 2, y, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text("This document certifies that the following expense has been approved for reimbursement.", W / 2, y + 7, { align: "center" });

  y += 16;
  doc.setDrawColor(221, 214, 254);
  doc.setLineWidth(0.5);
  doc.line(18, y, W - 18, y);

  y += 10;
  const empName  = reimbursement.user?.name  || user?.name  || "Employee";
  const empEmail = reimbursement.user?.email || user?.email || "—";
  const empRole  = reimbursement.user?.role  || user?.role  || "Employee";

  doc.setFillColor(245, 243, 255);
  doc.roundedRect(18, y, W - 36, 28, 5, 5, "F");
  doc.setFillColor(124, 58, 237);
  doc.roundedRect(18, y, 5, 28, 3, 3, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 27, 75);
  doc.text(empName, 28, y + 11);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(107, 114, 128);
  doc.text(`${empRole}  ·  ${empEmail}`, 28, y + 19);

  y += 38;
  doc.setFillColor(124, 58, 237);
  doc.roundedRect(18, y, W - 36, 18, 5, 5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(221, 214, 254);
  doc.text("APPROVED AMOUNT", 28, y + 7);
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text(`Rs. ${Number(reimbursement.amount).toLocaleString("en-IN")}`, 28, y + 15);

  y += 28;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(30, 27, 75);
  doc.text("Expense Details", 18, y);

  autoTable(doc, {
    startY: y + 5,
    head: [["Field", "Details"]],
    body: [
      ["Description",  reimbursement.description || "—"],
      ["Expense Date",  new Date(reimbursement.expenseDate).toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })],
      ["Amount",        `Rs. ${Number(reimbursement.amount).toLocaleString("en-IN")}`],
      ["Applied On",    new Date(reimbursement.createdAt).toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })],
      ["Status",        "APPROVED FOR REIMBURSEMENT"],
    ],
    headStyles: { fillColor: [124, 58, 237], textColor: [255, 255, 255], fontStyle: "bold", fontSize: 9, cellPadding: 5 },
    bodyStyles: { fontSize: 9, cellPadding: 5, textColor: [55, 65, 81] },
    alternateRowStyles: { fillColor: [245, 243, 255] },
    columnStyles: { 0: { fontStyle: "bold", textColor: [124, 58, 237], cellWidth: 40 } },
    styles: { lineColor: [221, 214, 254], lineWidth: 0.3 },
    margin: { left: 18, right: 18 },
    theme: "grid",
    didParseCell: (data) => {
      if (data.section === "body" && data.row.index === 4 && data.column.index === 1) {
        data.cell.styles.textColor = [5, 150, 105];
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fontSize  = 10;
      }
    },
  });

  let finalY = doc.lastAutoTable.finalY + 12;

  doc.setFillColor(209, 250, 229);
  doc.setDrawColor(16, 185, 129);
  doc.setLineWidth(1.2);
  doc.roundedRect(18, finalY, W - 36, 22, 7, 7, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(5, 150, 105);
  doc.text("REIMBURSEMENT OFFICIALLY APPROVED", W / 2, finalY + 9, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(16, 185, 129);
  doc.text("This certificate is system-generated by StaffSync and is valid without a physical signature.", W / 2, finalY + 16, { align: "center" });

  finalY += 32;
  doc.setDrawColor(209, 213, 219);
  doc.setLineWidth(0.4);
  doc.line(18, finalY + 18, 78, finalY + 18);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(124, 58, 237);
  doc.text("Employee Signature", 48, finalY + 24, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(107, 114, 128);
  doc.text(empName, 48, finalY + 30, { align: "center" });

  doc.line(W - 78, finalY + 18, W - 18, finalY + 18);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(124, 58, 237);
  doc.text("Finance / Accounts", W - 48, finalY + 24, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(107, 114, 128);
  doc.text("Authorized Signatory", W - 48, finalY + 30, { align: "center" });

  doc.setFillColor(245, 243, 255);
  doc.rect(0, H - 14, W, 14, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(107, 114, 128);
  doc.text(`StaffSync  |  Expense Report  |  ${new Date().toLocaleString("en-IN")}`, W / 2, H - 5, { align: "center" });

  const safeEmpName = empName.replace(/\s+/g, "_");
  doc.save(`ReimbursementSlip_${safeEmpName}.pdf`);
};

